# Generated by Django 5.0.3 on 2024-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                ("price", models.IntegerField(default=0)),
                ("category", models.CharField(max_length=10)),
            ],
        ),
    ]
